"🤖 bot":
  - "apps/bot/**"

"🖥️ website":
  - "apps/web/**"

"⚙️ actions":
  - ".github/workflows/**"

"📖 documentation":
  - "apps/web/docs/**"
  - "README.md"
  - "LICENSE"
  - ".env.example"
  - "config.example.yml"

"🔗 dependencies":
  - "**/package.json"
  - "**/pnpm-lock.yaml"
