name: 🐞 Bug report
description: See something that isn't quite right? File a bug report for it!
labels: ["🐞 bug"]
body:
  - type: markdown
    attributes:
      value: Thank you for taking time out of your day to file a bug report! Please fill this form out as completely as possible.
  - type: textarea
    attributes:
      label: What happened?
      description: Explain the bug that you came across in a clear and consise matter.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you expect to happen?
      description: Explain what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction steps
      description: How can we reliably reproduce the bug?
