name: "✨ Feature request"
description: Thought of a cool idea? Tell us about it!
labels: ["✨ enhancement"]
body:
  - type: markdown
    attributes:
      value: Thank you for taking time out of your day to file a feature request! Please fill out this form as completely as possible.
  - type: textarea
    attributes:
      label: Describe the feature you'd like to request
      description: Please describe the feature as clear and concise as possible. Remember to add context as to why you believe this feature is needed.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like to see
      description: Please describe the solution you would like to see. Adding example usage is a good way to provide context.
