blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://csmos.space/discord
    about: Join the Discord server and ask community members for help about anything related to csmos
